name: teste-project-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '11'
      - run: java CiProjetoApplication.java
